### ISSUE TITLE
Script returns errors

### ISSUE THREAD

**Issue by lnfel** [thehassantahir/Faceboom#18]
Using: python3
OS: macOS

Hi just testing out `faceboom`.
When I run:
```
python3 faceboom.py -t <PROFILE-ID> -w wlist.txt
```

It returns this error:
```python
[!] Error: not viewing HTML
```

I know this is an issue with `mechanize` but I am just a beginner with python so I could not debug this any further.

The second time I ran the faceboom script it gave a new error similar with  issue #13 :
```python
[!] Error: a bytes-like object is required, not 'str'
```

For now I'll try to fiddle around the code some more to see if I can make this work.

**Comment by lnfel** [comment]
Update:

The following error is now gone.
```python
[!] Error: not viewing HTML
```

But `[!] Error: a bytes-like object is required, not 'str'` is still happening.

**Comment by thehassantahir** [comment]
Hey @Infel 

This is not an issue of user agents or HTML viewer.

Issue: 

> The reason for the above error happens when useragent() randomly picks:
> Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (S60; SymbOS; Opera Mobi/23.348; U; en) Presto/2.5.25 Version/10.54

We are facing this issue because Facebook has updated its API and I am currently working on its token authentication process to fetch the profiles But the security update is to tight. 

Thanks for reaching out on the issue.

Happy Hacking!

**Comment by lnfel** [comment]
I see, thank you for the explanation. I will close my pull request then.
